name: macos

on:
  # Runs on all pushes
  push:
  # # A push is made to a GitHub Pages-enabled branch
  # page_build:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: macos-latest-${{ github.ref }}
  cancel-in-progress: true

env:
  DISPLAY: :0
  CMAKE_CONFIGURATION_TYPES: Debug;Release;RelWithDebInfo;MinSizeRel
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  VCPKG_MAX_CONCURRENCY: 3
  VCPKG_OSX_ARCHITECTURES: "x86_64"
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  BUILD_TYPE: Release
  BUILD_DIR: ${{ github.workspace }}/build
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_CACHE_MULTIARCH: 1
  SCCACHE_RECACHE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  RACK_SDK_VERSION: 2.5.2
  RACK_SDK_PLATFORM: "mac-x64+arm64"
  RACK_DIR: ${{ github.workspace }}/dep/Rack-SDK

jobs:
  macos:
    runs-on: macos-latest

    steps:

#     - name: Use latest Xcode on system (macOS)
#       uses: maxim-lobanov/setup-xcode@v1
#       with:
#         xcode-version: latest-stable
    
    - name: Checkout StoneyVCV code
      uses: actions/checkout@v4
      with:
        submodules: true
        
      # https://vcvrack.com/manual/Building#Setting-up-your-development-environment
    - name: Install VCV's macOS Deps
      run: |
        brew install git wget cmake autoconf automake libtool jq python zstd pkg-config sccache tree
        curl https://vcvrack.com/downloads/Rack-SDK-${{env.RACK_SDK_VERSION}}-${{env.RACK_SDK_PLATFORM}}.zip -o ./dep/Rack-SDK-${{env.RACK_SDK_VERSION}}-${{env.RACK_SDK_PLATFORM}}.zip
        cd dep
        unzip Rack-SDK-${{env.RACK_SDK_VERSION}}-${{env.RACK_SDK_PLATFORM}}.zip
        cd ..

    - name: Set Up Build Cache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Deps
      uses: johnwason/vcpkg-action@v6
      with:
        # vcpkg triplet to use
        triplet: x64-osx
        # Additional cache key component (optional)
        cache-key: macos-latest
        # GitHub token to authenticate API requests. Recommended to use  github.token 
        token: ${{ github.token }}
        # Directory containing vcpkg.json manifest file. Cannot be used with pkgs.
        manifest-dir: ${{ github.workspace }}
        # Use vcpkg built-in GitHub binary caching. If not specified, will use the dry-run based file cache.
        github-binarycache: true

    - name: Configure Tests
      run: >-
        cmake
        -S ${{ github.workspace }}
        -B ${{ env.BUILD_DIR }}
        -G "Unix Makefiles"
        -DCMAKE_BUILD_TYPE:STRING=${{ env.BUILD_TYPE }}
        -DCMAKE_INSTALL_PREFIX=${PWD}/install
        -DVCPKG_MANIFEST_MODE:STRING=ON
        -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
        -DCMAKE_C_COMPILER_LAUNCHER:STRING=sccache
        -DCMAKE_CXX_COMPILER_LAUNCHER:STRING=sccache
        -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64
        -DVCPKG_HOST_TRIPLET:STRING=x64-osx
        -DVCPKG_TARGET_TRIPLET:STRING=x64-osx
        --compile-no-warning-as-error
        --no-warn-unused-cli

    - name: Build Tests
      run: >-
        cmake
        --build ${{ github.workspace }}/build
        --clean-first
        -j3

    - name: Test
      run: >-
        cd build &&
        ctest
        -j3
        --rerun-failed
        --output-on-failure
        --verbose 
        && cd ..

    - name: Build
      run: make -j3

    - name: Install
      run: make install -j3

    - name: Dist
      run: make dist -j3

    - name: Tree
      run: tree

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: StoneyVCV-2.0.0-mac-x64.vcvplugin
        path: '${{ github.workspace }}/dist/StoneyVCV-2.0.0-mac-x64.vcvplugin'

    - name: Get Artifacts
      uses: actions/download-artifact@v4
