name: ubuntu

on:
  # Runs on all pushes
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ubuntu-latest-${{ github.ref }}
  cancel-in-progress: true

env:
  DISPLAY: :0
  BUILD_DIR: ${{ github.workspace }}/build
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  VCPKG_MAX_CONCURRENCY: 3
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  SCCACHE_GHA_ENABLED: "true"
  RACK_SDK_VERSION: 2.5.2
  RACK_SDK_PLATFORM: "lin-x64"

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:

      # REQUIREMENTS

    - name: Checkout StoneyVCV code
      uses: actions/checkout@v4
      with:
        submodules: true

      # https://vcvrack.com/manual/Building#Setting-up-your-development-environment
    - name: Install VCV's Linux Deps
      run: |
        sudo apt-get update && sudo apt install unzip git gdb curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libgtk-3-dev libjack-jackd2-dev jq zstd libpulse-dev pkg-config ninja-build ccache tree

      # DEVELOPER WORKFLOW

    - name: vcpkg install
      uses: johnwason/vcpkg-action@v6
      with:
        # vcpkg triplet to use
        triplet: x64-linux
        # GitHub token to authenticate API requests. Recommended to use  github.token
        token: ${{ github.token }}
        # Directory containing vcpkg.json manifest file. Cannot be used with pkgs.
        manifest-dir: ${{ github.workspace }}
        # Use vcpkg built-in GitHub binary caching. If not specified, will use the dry-run based file cache.
        github-binarycache: false
        pkgs: catch2 simde vcpkg-cmake-config vcpkg-cmake

    - name: Configure Tests
      run: >-
        cmake
        --preset x64-linux-release
        --fresh

    - name: Build Tests
      run: >-
        cmake
        --build ${{ env.BUILD_DIR }}
        --target tests
        -j3

    - name: Test
      run: >-
        cd ${{ env.BUILD_DIR }} &&
        ctest
        -j3
        --rerun-failed
        --output-on-failure
        --verbose
        && cd ${{ github.workspace }}

      # DEPLOYMENT WORKFLOW

    - name: Fetch Rack SDK
      run: |
        curl https://vcvrack.com/downloads/Rack-SDK-${{env.RACK_SDK_VERSION}}-${{env.RACK_SDK_PLATFORM}}.zip -o ./dep/Rack-SDK-${{env.RACK_SDK_VERSION}}-${{env.RACK_SDK_PLATFORM}}.zip
        cd dep
        unzip Rack-SDK-${{env.RACK_SDK_VERSION}}-${{env.RACK_SDK_PLATFORM}}.zip
        cd ..

    - name: Build
      env:
        RACK_DIR: ${{ github.workspace }}/dep/Rack-SDK
      run: make -j3

    - name: Dist
      env:
        RACK_DIR: ${{ github.workspace }}/dep/Rack-SDK
      run: make dist -j3

    - name: Install
      env:
        RACK_DIR: ${{ github.workspace }}/dep/Rack-SDK
      run: make install -j3

    # List all files in tree
    - name: Tree
      run: tree

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: StoneyDSP-StoneyVCV-2.0.1-lin-x64.vcvplugin
        path: ${{ github.workspace }}/dist/StoneyDSP-StoneyVCV-2.0.1-lin-x64.vcvplugin

    - name: Get Artifacts
      uses: actions/download-artifact@v4
